### ISSUE TITLE
TypeError - Ticker, stock_id

### ISSUE THREAD

**Issue by boyac** [linsamtw/FinMind#1]
Hi, there's a TypeError. However, it's not quite clear where should I input the stock_id. Thanks

super(ClassTaiwanStockPrice, self).__init__(TABLE,'stock_id')
TypeError: super() argument 1 must be type, not classobj

**Comment by linsamtw** [comment]
what's you code?
paste on here

**Comment by linsamtw** [comment]
oh! I get it.
e.g :
data = Load.FinData(dataset = 'TaiwanStockPrice',select = ['2330.TW'],date = '2018-10-10')

the stock_id is '2330.TW'

but how to know other stock_id ?
TaiwanStockInfo = Load.FinData(dataset = 'TaiwanStockInfo')
print( TaiwanStockInfo['stock_id'] )
