### ISSUE TITLE
[請益] 爬蟲相關

### ISSUE THREAD

**Issue by frankShih** [linsamtw/FinMind#11]
你好，

我看程式的部分，資料是從 DB 倒出來處理
因此，想請教一下，爬蟲代碼的部分是否也有開源?

另外，DB 是自己 own 的嗎?
如果是，要如何評估，若有大量用戶 access 你們的資料，而 DB 依然保持穩健?

PS 因為我自己也有寫類似的東西，但是開發得很卡，爬蟲經常被阻擋。所以想找其他人學習 XD

**Comment by linsamtw** [comment]
爬蟲部分沒有開源，因為用到分散式 + insert db，有密碼問題，有興趣可以

如果你遇到大量用戶，可以使用 nginx 多核心，再加上 haproxy 做 loading balance

爬蟲被擋，我初期也有遇到，用分散式可以解決這個問題

有興趣可以參考這篇
https://github.com/linsamtw/RabbitmqCelery

分散式除了 code，node 部屬佔很大部分
