### ISSUE TITLE
TX futures all day data?

### ISSUE THREAD

**Issue by gg50903** [linsamtw/FinMind#15]
經過測試stock id 打 TX
可以拉到大台的每秒資料，但是是不是沒辦法得到台指期夜盤的資料呢

**Comment by gg50903** [comment]
另外，我看到date的時間標記最小單位是秒，但是有沒有可能一秒內出現多筆tick
這樣他的price與volume是標記哪一個點呢?

**Comment by linsamtw** [comment]
> 另外，我看到date的時間標記最小單位是秒，但是有沒有可能一秒內出現多筆tick
> 這樣他的price與volume是標記哪一個點呢?

台股證交所，目前架構是5秒集合競價，因此不可能出現，1秒之內多次交易。

**Comment by linsamtw** [comment]
> 經過測試stock id 打 TX
> 可以拉到大台的每秒資料，但是是不是沒辦法得到台指期夜盤的資料呢

台指期，算在期貨中，未來會爬取歷史 daily data，目前只有交易明細

    import requests
    import pandas as pd
    url = 'http://finmindapi.servebeer.com/api/data'
    form_data = {'dataset':'TaiwanFutures',
         'stock_id':'MTX',
         'date':'2019-09-02',
         }

    res = requests.post(
      url,verify = True,
      data = form_data)

    temp = res.json()
    data = pd.DataFrame(temp['data'])
    data.head()

**Comment by gg50903** [comment]
台指期並不是5秒競價，是逐筆撮合
所以會有1秒內多個tick的情況
我用的param是
form_data = {'dataset':'TaiwanFutures',
     'stock_id':'TX',
     'date':'2019-09-02',
     }
來抓取大台的資料，拉下來的資料時間戳記最小單位是秒，而不是tick
所以這是我的疑問

**Comment by linsamtw** [comment]
> 台指期並不是5秒競價，是逐筆撮合
> 所以會有1秒內多個tick的情況
> 我用的param是
> form_data = {'dataset':'TaiwanFutures',
> 'stock_id':'TX',
> 'date':'2019-09-02',
> }
> 來抓取大台的資料，拉下來的資料時間戳記最小單位是秒，而不是tick
> 所以這是我的疑問

你是對的，我資料來源是，期交所，他們時間最小只有秒，所以會出現一種情況，一秒內多次交易

之前我以為是重複資料，把它刪除，

我正在修正這塊，未來會加入 index，雖然無法知道，一秒內交易狀況，不過至少有個排序，如果期交所是按照資料時間做排序，那 index 小的，就是先交易的
