### ISSUE TITLE
資料來源

### ISSUE THREAD

**Issue by machineCYC** [linsamtw/FinMind#5]
能否新增金融數據是來自於哪個網站的資料呢？

例如：
證券交易所 (TWSE)(http://www.twse.com.tw/zh/)
證券櫃台買賣中心 (TPEX)(http://www.tpex.org.tw/web/index.php?l=zh-tw)

**Comment by linsamtw** [comment]
由於是爬蟲抓資料，可能有被檔的風險，可以提供部分 data source

三大法人買賣 : http://www.tpex.org.tw/web/index.php?l=zh-tw
台股融資融券 : http://www.twse.com.tw/zh/
國際油價 : https://www2.moeaboe.gov.tw/oil102/oil2017/newmain.asp
匯率 : https://www.ofx.com/en-au/
債券 : https://www.investing.com/
