### ISSUE TITLE
database TaiwanStockPrice  disappear

### ISSUE THREAD

**Issue by machineCYC** [linsamtw/FinMind#7]
Does anyone have this error?

pymysql.err.InternalError: (1049, "Unknown database 'TaiwanStockPrice'")

When I run below code

from FinMind.Data import Load
TaiwanStockInfo = Load.FinData(dataset = 'TaiwanStockInfo')

**Comment by linsamtw** [comment]
please update latest package
pip install -U FinMind

**Comment by machineCYC** [comment]
@linsamtw thanks! Fix the problem.
