### ISSUE TITLE
大盤指數

### ISSUE THREAD

**Issue by machineCYC** [linsamtw/FinMind#9]
請問是不是沒有各國大盤指數的資料呢?

**Comment by linsamtw** [comment]
你想要什麼大盤指數，我試試看加入 package 中

**Comment by machineCYC** [comment]
台灣大盤指數 http://www.twse.com.tw/zh/page/trading/indices/MI_5MINS_HIST.html
美國指數道瓊、S&P500...等

**Comment by linsamtw** [comment]
好，近期會加上去

**Comment by linsamtw** [comment]
預計這周完成

**Comment by linsamtw** [comment]
^TWII 台股大盤
^GSPC  SP500
^DJI  道瓊

上述以加入

**Comment by frankShih** [comment]
@linsamtw  請問一下，

https://api.finmindtrade.com/api/v3/data?dataset=TaiwanStockPrice&date=2020-10-01&stock_id=TWII

request OK，但是沒有 data
是我有哪邊設定錯誤嗎?

**Comment by linsamtw** [comment]
大盤代碼是^TWII，股票代碼可以用台股總覽查詢

frankShih <notifications@github.com>於 2020年10月8日 週四，上午8:58寫道：

**Comment by frankShih** [comment]
@linsamtw 
請問這兩天資料是否出現異常?

再麻煩協助確認了，感謝

**Comment by linsamtw** [comment]
大盤嗎?
已修復

**Comment by frankShih** [comment]
> 大盤嗎?
> 已修復

是的，感謝!

**Comment by linsamtw** [comment]
大盤代碼，目前是^TWII，兩周後會改成 TWII，你可以先修改 code，避免未來拿不到 data

**Comment by linsamtw** [comment]
大盤代碼，目前是^TWII，兩周後會改成 TWII，你可以先修改 code，避免未來拿不到 data

**Comment by frankShih** [comment]
> 大盤代碼，目前是^TWII，兩周後會改成 TWII，你可以先修改 code，避免未來拿不到 data

感謝您的熱心提醒

**Comment by linsamtw** [comment]
> > 大盤代碼，目前是^TWII，兩周後會改成 TWII，你可以先修改 code，避免未來拿不到 data
> 
> 感謝您的熱心提醒

不好意思，可能會再做修正，

由於未來計畫增加，櫃買指數等其他的指數，為了命名方面，改採用證交所的命名

加權指數 id 會改為，TAIEX
未來新增櫃買指數，id 為 TPEx
